CREATE TABLE public.apostador
(
    id int GENERATED BY DEFAULT AS IDENTITY,
    email character varying(64) NOT NULL,
    numeros character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE numero_aposta
(
    id_numero_aposta int GENERATED BY DEFAULT AS IDENTITY,
    id_apostador int NOT NULL,
    numeros character varying(255),

    PRIMARY KEY (id_numero_aposta),
    CONSTRAINT id_apostador_fkey
    FOREIGN KEY(id_apostador) REFERENCES apostador(id)
);